version: "3"

services:
    target_1:
        image: "${IMAGE_BASE_TAG:?err}"
        container_name: target_1
        hostname: target_1
        labels:
            operation-mode: "target"
        expose:
            - "9997/tcp"
        volumes:
            - target_1:/app
        networks:
            - "${NETWORK:?err}"
        command: ["node", "app.js", "target"]
    target_2:
        image: "${IMAGE_BASE_TAG:?err}"
        container_name: target_2
        hostname: target_2
        labels:
            operation-mode: "target"
        expose:
            - "9997/tcp"
        volumes:
            - target_2:/app
        networks:
            - "${NETWORK:?err}"
        command: ["node", "app.js", "target"]
    splitter:
        image: "${IMAGE_BASE_TAG:?err}"
        container_name: splitter
        hostname: splitter
        labels:
            operation-mode: "splitter"
        expose:
            - "9997/tcp"
        networks:
            - "${NETWORK:?err}"
        command: ["node", "app.js", "splitter"]
        depends_on:
            - target_1
            - target_2

networks:
    timbernet:
        name: "${NETWORK:?err}"

volumes:
    target_1:
    target_2: