name: Assignment-CI

on:
  # Triggers the workflow on push or manual
  push:
  workflow_dispatch:

env:
  IMAGE_BASE_TAG: cribl/app-image
  NETWORK: timbernet
  WORKING_DIR: /app
  VOLUME: data

jobs:
  integration-tests:
    strategy:
      fail-fast: false
      matrix:
        node: [ 17, 16, 14 ]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build App Image
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: node_version=${{ matrix.node }}
          tags: ${{ env.IMAGE_BASE_TAG }}
          file: src/docker/app.Dockerfile
          load: true

      - name: Install Requirements
        run: pip3 install -r requirements.txt

      - name: Create Versioned Artifacts Dir
        run: mkdir src/reports/v${{ matrix.node}}

      - name: Run Integration Tests
        run: python3 -m pytest --artifacts=src/reports/v${{ matrix.node}} --junit-xml=src/reports/v${{ matrix.node }}-assignment-ci.xml

      - name: Upload Reports/Artifacts
        if: success() || failure()
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: src/reports/*.tar.gz

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: JUnit Tests (${{ matrix.node }})
          path: src/reports/*.xml
          reporter: java-junit
          fail-on-error: 'false'
